ALTER TABLE QUESTION ALTER COLUMN ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT;
ALTER TABLE `USER` ALTER COLUMN ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT;
ALTER TABLE COMMENT ALTER COLUMN COMMENTATOR BIGINT NOT NULL;
ALTER TABLE QUESTION ALTER COLUMN CREATOR BIGINT;